### ISSUE TITLE
jpinyin-1.1.5  mutil_pinyin 中出现个别拼音字符为 阿尔法符号

### ISSUE THREAD

**Issue by chorar** [stuxuhai/jpinyin#15]
乌拉=wù,lɑ
苤蓝=piě,lɑn
排场=pái,chɑng

**Comment by chorar** [comment]
还有部分拼音音标放置的位置不对
空白=kòng,baí (错误)
空白=kòng,bái (正确)

汉语拼音声调标注规则:
（1）有a不放过； （2）没a找o、e； （3）i、u并列标在后； （4）单个韵母不必说

**Comment by stuxuhai** [comment]
已修复，非常感谢反馈
