### ISSUE TITLE
朩

### ISSUE THREAD

**Issue by Fumanix** [stuxuhai/jpinyin#17]
朩  解析异常

**Comment by stuxuhai** [comment]
可以添加用户自定义词典，比如：
词典文件：user.dict 
文件内容：
朩=tin

然后加载自定义词典即可解析了
PinyinHelper.addPinyinDict("user.dict")

**Comment by ShaomingLi** [comment]
能否在这种情况下不抛出java.lang.ArrayIndexOutOfBoundsException，或者抛出一个信息明确一些的异常

**Comment by stuxuhai** [comment]
@ShaomingLi 感谢建议，已更新
