### ISSUE TITLE
建议相关方法返回的string去掉空白字符

### ISSUE THREAD

**Issue by workjm** [stuxuhai/jpinyin#19]
我遇到的问题是有个应用名称 为了显示在列表的前面，故意把应用名称字段加了Unicode空白的字符。

所以：

convertToPinyinString 方法建议返回的string去掉空白字符。

public static String test(String str) {
        final StringBuilder sb = new StringBuilder();
        int length = str.length();
        for (int i=0; i<length; i++) {
            final char character = str.charAt(i);
            if (!Character.isSpaceChar(character)) {
                sb.append(character);
            }
        }
        return sb.toString();
    }
测试方法

**Comment by stuxuhai** [comment]
对于不能转为拼音的字符，jpinyin是直接返回该字符的。像去掉空白字符这样的特定的逻辑就需要自己处理了

**Comment by workjm** [comment]
好吧，只是建议而已，因为个人觉得转成拼音后的字符串，存在这种空白字符，没有存在的意义。

**Comment by YiweiCai** [comment]
个人觉得还是很有必要的，因为存在空格的时候，我们还可以做一个分词的感觉





--

致礼。
Yiwei Cai


在 2016-08-23 08:47:24，"workjm" <notifications@github.com> 写道：


好吧，只是建议而已，因为个人觉得转成拼音后的字符串，存在这种空白字符，没有存在的意义。

**Comment by litianyuan1111** [comment]
直接中间加空格，然后用字符处理方式去掉空格不就对了
