### ISSUE TITLE
如何将“成长”转为“chengzhang”

### ISSUE THREAD

**Issue by jimhan** [stuxuhai/jpinyin#23]
你好，请问如何将“成长”转为“cheng zhang”？

**Comment by stuxuhai** [comment]
对于一些多音字，如果默认拼音库不能正确转换的，可以添加用户自定义字典：
创建用户自定义字典文件：user.dict
文件内容：成长=chéng,zhǎng

PinyinHelper.addMutilPinyinDict("user.dict");

之后就可以正确转换了
