### ISSUE TITLE
测试“乐器”时输出错误

### ISSUE THREAD

**Issue by lkfs** [stuxuhai/jpinyin#7]
String str = "乐器";
System.out.println( PinyinHelper.convertToPinyinString(str, ",", PinyinFormat.WITH_TONE_MARK) ); //yuè,pǔ
System.out.println( PinyinHelper.convertToPinyinString(str, ",", PinyinFormat.WITH_TONE_NUMBER) ); //yue4,pu3
System.out.println( PinyinHelper.convertToPinyinString(str, ",", PinyinFormat.WITHOUT_TONE) ); //yue,pu
System.out.println( PinyinHelper.getShortPinyin(str) ); //yp

**Comment by stuxuhai** [comment]
@lkfs 已修复，资源文件中标错了拼音，感谢反馈
